#!/bin/bash

if [ -x "$(command -v nmap)" ]; then
  sudo apt install nmap
fi

for ip in $(nmap -n -sn 192.168.1.0/26 -oG - | awk '/Up$/{print $2}'); do
  echo "looking at $ip"
  ssh ubuntu@$ip 'git clone https://github.com/wildfireone/piArray && cd piArray && bash setup.sh'
done
